name: CI Practice

on: push

jobs:
  hello:
    runs-on: self-hosted

    steps:
      - name: print a message
        run: echo "Hello CI/CD!"

  deploy:
    needs: hello
    runs-on: self-hosted

    steps:
      - name: deploy message
        run: echo "Deploying now!"

  greet:
    runs-on: self-hosted

    steps:
      - name: greet with env variable
        env:
          MY_NAME: Manar
        run: echo "Hello, $MY_NAME!"

  show_secret:
    runs-on: self-hosted

    steps:
      - name: print secret message
        env:
          MY_SECRET: ${{ secrets.MY_SECRET_MESSAGE }}
        run: echo "The Secret is: $ MY_SECRET"